# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./TuringEmulator Project
      run: dotnet restore
    - name: Release win-x64
      working-directory: ./TuringEmulator Project
      run: dotnet build --runtime win-x64 --configuration Release
    - name: Release win-x32
      working-directory: ./TuringEmulator Project
      run: dotnet build --runtime win-x86 --configuration Release
    - name: Release win-Arm
      working-directory: ./TuringEmulator Project
      run: dotnet build --runtime win-arm64 --configuration Release
